--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/fuyutsuki/Texter
branches:
  - master
  - api/4.0
projects:
  Texter:
    path: ""
    icon: "/assets/Logo.png"
    libs:
      - src: fuyutsuki/libform/libform
        version: 0.4.0
        branch: "4.0"
...
